### ISSUE TITLE
wiki

### ISSUE THREAD

**Issue by Mvkbesteu** [CubBossa/PathFinder#13]
Hi,

The usage of the plugin is unclear to me, is there some sort of a wiki?

Thanks

**Comment by CubBossa** [comment]
Hey, there is no full documentation yet. To get started, there is a file in your plugins folder that tells you about the first steps. If there is anything unclear in particular, feel free to ask here and i can give you a detailed explanation!

**Comment by CubBossa** [comment]
The documentation can be found [here](https://docs.leonardbausenwein.de/getting_started/introduction.html). Files that are not yet fully created named "WIP - ...", but I plan to finish it within the next days
