### ISSUE TITLE
Issues with selectors

### ISSUE THREAD

**Issue by MomoPewpew** [CubBossa/PathFinder#75]
Hello!

First of all, love the plugin. Spent an entire day mapping out my server, and I'm in love with the result

But I noticed that there's some issues with the selectors

I can't get the selectors for group, world or id to parse properly at all. They just give me errors in using the command

Sorting doesn't seem to do anything at all

Offset, limit and distance seem to work fine

**Comment by MomoPewpew** [comment]
[dump_2024-04-01_20-59-23.json](https://github.com/CubBossa/PathFinder/files/14828494/dump_2024-04-01_20-59-23.json)
Certainly!

**Comment by MomoPewpew** [comment]
I made a PR that fixes the issue for the group selector

**Comment by CubBossa** [comment]
Thanks for having a closer look and for the PR, means a lot to me if people participate in the project!
 Just 2 days ago I started a big cleanup for 5.0.0, renaming some classes and stuff. I'll need one more day to make sure I don't bring in regressions but then I'll have a close look at the selector.
A quick peek on the world filter showed that I compared UUID with World object :P
`Objects.equals(node.getLocation().getWorld(), c.getValue().getUID())`

**Comment by CubBossa** [comment]
Quick list so I don't forget a thing:
- Check sorting depending on location in selection string
- Limit Argument modifies order of list elements?
- Check ID argument
- Check World argument (equals with world and uuid)
- Check NamespacedKey (fixed in PR, ':' was invalid char)

**Comment by CubBossa** [comment]
Only bug remaining is that `limit=1,offset=1` results in something different than `offset=1,limit=1`. To fix this, I must allow attributes to specify "runbefore" attributes.
