### ISSUE TITLE
Moving aborts navigation

### ISSUE THREAD

**Issue by DaniDipp** [CubBossa/PathFinder#80]
When I move my character or the camera, the navigation stops. How can I make sure the navigation stays active until I'm at the destination?

https://youtu.be/5oPpDLhpAB0
[dump_2024-06-29_02-50-31.json](https://github.com/user-attachments/files/16038568/dump_2024-06-29_02-50-31.json)

**Comment by DaniDipp** [comment]
there is no console output

**Comment by CubBossa** [comment]
Thank you very much for reporting. Did it happen after upgrading any plugins or the server?

**Comment by MomoPewpew** [comment]
Hi!

I'm on DaniDipp's team and we did some investigating into this bug. I've made a PR with a fix.

https://github.com/CubBossa/PathFinder/pull/81

**Comment by bale1017** [comment]
Awesome, thank you very much!
Don't worry about the build failing in the PR, there's something off with the check in general. I'll merge and release later today or tomorrow
